server:
  port: 7970
spring:
  application:
    name: inter-hsp-txmanager
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.10.10.100:3307/internethsp?useUnicode=true&characterEncoding=UTF-8
    username: root
    password:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create-drop
#redis 主机
  redis:
    host: 10.10.10.250
  #redis 端口
    port: 6379
  #redis 密码

    password:

# TM后台登陆密码
tx-lcn:
  manager:
    admin-key: 123456

    host: 127.0.0.1
    port: 8070

# 开启日志,默认为false
  logger:
   enabled: true
   driver-class-name: ${spring.datasource.driver-class-name}
   jdbc-url: ${spring.datasource.url}
   username: ${spring.datasource.username}
   password: ${spring.datasource.password}
logging:
  level:
    com:
      codingapi:
        txlcn: DEBUG

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url.defaultZone: http://admin:admin@127.0.0.1:9092/eureka/eureka

